Repository OCA/survey, pull requests merged in 2022-11, with the labels that each got.

#54 Updated from template
  .copier-answers.yml
  .github/workflows/test.yml
  .travis.yml
  README.md
Labels: needs review, approved, ready to merge

#59 [13.0] Update from template
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  requirements.txt
  survey_question_type_five_star/README.rst
  survey_question_type_five_star/readme/DEVELOP.rst
  survey_question_type_five_star/readme/HISTORY.rst
  survey_question_type_five_star/readme/INSTALL.rst
  survey_question_type_five_star/readme/ROADMAP.rst
  survey_question_type_five_star/readme/USAGE.rst
  survey_question_type_five_star/static/description/index.html
  survey_resource_booking/__manifest__.py
  test-requirements.txt
Labels: bot is merging ⏳

#50 [MIG] survey_description: Migration to 13.0
  setup/survey_description/odoo/addons/survey_description
  setup/survey_description/setup.py
  survey_description/README.rst
  survey_description/__init__.py
  survey_description/__manifest__.py
  survey_description/i18n/survey_description.pot
  survey_description/readme/CONTRIBUTORS.rst
  survey_description/readme/CREDITS.rst
  survey_description/readme/DESCRIPTION.rst
  survey_description/readme/USAGE.rst
  survey_description/static/description/icon.png
  survey_description/static/description/icon.svg
  survey_description/static/description/index.html
  survey_description/static/src/js/fields_form_page_description.js
  survey_description/views/assets.xml
  survey_description/views/survey_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#61 [FIX] survey_question_type_five_star: Fix readme
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  survey_question_type_five_star/README.rst
  survey_question_type_five_star/readme/DEVELOP.rst
  survey_question_type_five_star/readme/HISTORY.rst
  survey_question_type_five_star/readme/INSTALL.rst
  survey_question_type_five_star/readme/ROADMAP.rst
  survey_question_type_five_star/readme/USAGE.rst
  survey_question_type_five_star/static/description/index.html
Labels: bot is merging ⏳

#47 [MIG] survey_question_type_nps: Migration to 14.0
  setup/survey_question_type_nps/odoo/addons/survey_question_type_nps
  setup/survey_question_type_nps/setup.py
  survey_question_type_nps/README.rst
  survey_question_type_nps/__init__.py
  survey_question_type_nps/__manifest__.py
  survey_question_type_nps/models/__init__.py
  survey_question_type_nps/models/survey_question.py
  survey_question_type_nps/models/survey_user_input_line.py
  survey_question_type_nps/readme/CONTRIBUTORS.rst
  survey_question_type_nps/readme/DESCRIPTION.rst
  survey_question_type_nps/static/description/icon.png
  survey_question_type_nps/static/src/js/survey.js
  survey_question_type_nps/static/src/scss/parameters.scss
  survey_question_type_nps/static/src/scss/survey.scss
  survey_question_type_nps/templates/survey_template.xml
  survey_question_type_nps/tests/__init__.py
  survey_question_type_nps/tests/test_survey.py
  survey_question_type_nps/views/survey_question.xml
Labels: approved, ready to merge, bot is merging ⏳

#60 [MIG][14.0] survey_description: Migration to 14.0
  setup/survey_description/odoo/addons/survey_description
  setup/survey_description/setup.py
  survey_description/README.rst
  survey_description/__init__.py
  survey_description/__manifest__.py
  survey_description/i18n/survey_description.pot
  survey_description/readme/CONTRIBUTORS.rst
  survey_description/readme/CREDITS.rst
  survey_description/readme/DESCRIPTION.rst
  survey_description/readme/ROADMAP.rst
  survey_description/readme/USAGE.rst
  survey_description/static/description/icon.png
  survey_description/static/description/icon.svg
  survey_description/static/description/index.html
  survey_description/views/survey_views.xml
Labels: approved

#55 [ADD] survey_xlsx
  setup/survey_xlsx/odoo/addons/survey_xlsx
  setup/survey_xlsx/setup.py
  survey_xlsx/__init__.py
  survey_xlsx/__manifest__.py
  survey_xlsx/models/__init__.py
  survey_xlsx/models/survey_user_input_line.py
  survey_xlsx/readme/CONTRIBUTORS.rst
  survey_xlsx/readme/DESCRIPTION.rst
  survey_xlsx/report/__init__.py
  survey_xlsx/report/report_survey_xlsx.py
  survey_xlsx/report/report_survey_xlsx.xml
  survey_xlsx/tests/__init__.py
  survey_xlsx/tests/test_report.py
Labels: needs review, approved, ready to merge, bot is merging ⏳
