Repository OCA/survey, pull requests merged in 2023-08, with the labels that each got.

#81 [15.0][MIG] survey_contact_generation: Migration to version 15.0
  setup/survey_contact_generation/odoo/addons/survey_contact_generation
  setup/survey_contact_generation/setup.py
  survey_contact_generation/README.rst
  survey_contact_generation/__init__.py
  survey_contact_generation/__manifest__.py
  survey_contact_generation/demo/survey_contact_generation_demo.xml
  survey_contact_generation/i18n/es.po
  survey_contact_generation/i18n/survey_contact_generation.pot
  survey_contact_generation/models/__init__.py
  survey_contact_generation/models/survey_question.py
  survey_contact_generation/models/survey_survey.py
  survey_contact_generation/models/survey_user_input.py
  survey_contact_generation/readme/CONFIGURE.rst
  survey_contact_generation/readme/CONTRIBUTORS.rst
  survey_contact_generation/readme/DESCRIPTION.rst
  survey_contact_generation/readme/USAGE.rst
  survey_contact_generation/static/description/icon.png
  survey_contact_generation/static/description/index.html
  survey_contact_generation/static/tests/survey_contact_generation_tour.js
  survey_contact_generation/tests/__init__.py
  survey_contact_generation/tests/test_survey_contact_generation.py
  survey_contact_generation/views/survey_question_views.xml
  survey_contact_generation/views/survey_survey_views.xml
Labels: bot is merging ⏳

#89 [14.0][ADD] survey_question_type_binary
  setup/survey_question_type_binary/odoo/addons/survey_question_type_binary
  setup/survey_question_type_binary/setup.py
  survey_question_type_binary/README.rst
  survey_question_type_binary/__init__.py
  survey_question_type_binary/__manifest__.py
  survey_question_type_binary/i18n/survey_question_type_binary.pot
  survey_question_type_binary/models/__init__.py
  survey_question_type_binary/models/survey_question.py
  survey_question_type_binary/models/survey_user_input.py
  survey_question_type_binary/models/survey_user_input_line.py
  survey_question_type_binary/models/survey_user_input_line_binary.py
  survey_question_type_binary/readme/CONFIGURE.rst
  survey_question_type_binary/readme/CONTRIBUTORS.rst
  survey_question_type_binary/readme/DESCRIPTION.rst
  survey_question_type_binary/security/ir.model.access.csv
  survey_question_type_binary/static/description/icon.png
  survey_question_type_binary/static/description/index.html
  survey_question_type_binary/static/src/js/survey_form.js
  survey_question_type_binary/templates/survey_template.xml
  survey_question_type_binary/tests/__init__.py
  survey_question_type_binary/tests/test_survey.py
  survey_question_type_binary/views/survey_question.xml
  survey_question_type_binary/views/survey_user_input_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#95 [MIG] survey_legal: Migration to 15.0
  setup/survey_legal/odoo/addons/survey_legal
  setup/survey_legal/setup.py
  survey_legal/README.rst
  survey_legal/__init__.py
  survey_legal/__manifest__.py
  survey_legal/controllers/__init__.py
  survey_legal/controllers/main.py
  survey_legal/i18n/survey_legal.pot
  survey_legal/models/__init__.py
  survey_legal/models/survey.py
  survey_legal/models/survey_user_input.py
  survey_legal/readme/CONFIGURE.rst
  survey_legal/readme/CONTRIBUTORS.rst
  survey_legal/readme/DESCRIPTION.rst
  survey_legal/static/description/icon.png
  survey_legal/static/description/index.html
  survey_legal/static/src/js/survey_form.esm.js
  survey_legal/views/survey_templates.xml
  survey_legal/views/survey_user_input_views.xml
  survey_legal/views/survey_views.xml
Labels: needs review, approved, bot is merging ⏳
