Repository OCA/survey, pull requests merged in 2025-05, with the labels that each got.

#115 [15.0][ADD] survey_next_survey_update_partner: new module
  setup/survey_next_survey_update_partner/odoo/addons/survey_next_survey_update_partner
  setup/survey_next_survey_update_partner/setup.py
  survey_next_survey_update_partner/README.rst
  survey_next_survey_update_partner/__init__.py
  survey_next_survey_update_partner/__manifest__.py
  survey_next_survey_update_partner/demo/survey_update_generated_partner_demo.xml
  survey_next_survey_update_partner/models/__init__.py
  survey_next_survey_update_partner/models/survey_user_input.py
  survey_next_survey_update_partner/readme/CONTEXT.md
  survey_next_survey_update_partner/readme/CONTRIBUTORS.md
  survey_next_survey_update_partner/readme/DESCRIPTION.md
  survey_next_survey_update_partner/readme/USAGE.md
  survey_next_survey_update_partner/static/description/index.html
  survey_next_survey_update_partner/static/tests/survey_contact_update_tour.esm.js
  survey_next_survey_update_partner/tests/__init__.py
  survey_next_survey_update_partner/tests/test_next_survey_update_partner.py
Labels: approved, bot is merging ⏳

#166 [17.0][MIG] survey_legal: Migration to version 17.0
  survey_legal/README.rst
  survey_legal/__init__.py
  survey_legal/__manifest__.py
  survey_legal/controllers/__init__.py
  survey_legal/controllers/main.py
  survey_legal/i18n/es.po
  survey_legal/i18n/it.po
  survey_legal/i18n/survey_legal.pot
  survey_legal/models/__init__.py
  survey_legal/models/survey.py
  survey_legal/models/survey_user_input.py
  survey_legal/pyproject.toml
  survey_legal/readme/CONFIGURE.md
  survey_legal/readme/CONTRIBUTORS.md
  survey_legal/readme/DESCRIPTION.md
  survey_legal/static/description/icon.png
  survey_legal/static/description/index.html
  survey_legal/static/src/js/survey_form.esm.js
  survey_legal/static/tests/survey_legal_tour.esm.js
  survey_legal/tests/__init__.py
  survey_legal/tests/test_survey_legal.py
  survey_legal/views/survey_templates.xml
  survey_legal/views/survey_user_input_views.xml
  survey_legal/views/survey_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#168 [16.0][IMP] partner_survey: add a wizard to share surveys with partners
  partner_survey/README.rst
  partner_survey/__init__.py
  partner_survey/__manifest__.py
  partner_survey/readme/CONTRIBUTORS.rst
  partner_survey/readme/DESCRIPTION.rst
  partner_survey/security/ir.model.access.csv
  partner_survey/static/description/index.html
  partner_survey/views/res_partner_view.xml
  partner_survey/wizard/__init__.py
  partner_survey/wizard/take_survey.py
  partner_survey/wizard/take_survey.xml
Labels: approved, bot is merging ⏳

#169 [17.0][MIG] survey_crm_sale_generation: Migration to version 17.0
  survey_crm_sale_generation/README.rst
  survey_crm_sale_generation/__init__.py
  survey_crm_sale_generation/__manifest__.py
  survey_crm_sale_generation/demo/survey_sale_demo.xml
  survey_crm_sale_generation/i18n/es.po
  survey_crm_sale_generation/i18n/it.po
  survey_crm_sale_generation/i18n/survey_crm_sale_generation.pot
  survey_crm_sale_generation/models/__init__.py
  survey_crm_sale_generation/models/sale_order.py
  survey_crm_sale_generation/models/survey_user_input.py
  survey_crm_sale_generation/pyproject.toml
  survey_crm_sale_generation/readme/CONFIGURE.md
  survey_crm_sale_generation/readme/CONTRIBUTORS.md
  survey_crm_sale_generation/readme/DESCRIPTION.md
  survey_crm_sale_generation/readme/USAGE.md
  survey_crm_sale_generation/static/description/icon.png
  survey_crm_sale_generation/static/description/index.html
  survey_crm_sale_generation/tests/__init__.py
  survey_crm_sale_generation/tests/test_survey_crm_sale_generation.py
Labels: approved, bot is merging ⏳

#170 [17.0][MIG] survey_certification_sending: Migration to version 17.0
  survey_certification_sending/README.rst
  survey_certification_sending/__init__.py
  survey_certification_sending/__manifest__.py
  survey_certification_sending/i18n/es.po
  survey_certification_sending/i18n/survey_certification_sending.pot
  survey_certification_sending/models/__init__.py
  survey_certification_sending/models/mail_template.py
  survey_certification_sending/models/survey_survey.py
  survey_certification_sending/models/survey_user_input.py
  survey_certification_sending/pyproject.toml
  survey_certification_sending/readme/CONTRIBUTORS.md
  survey_certification_sending/readme/DESCRIPTION.md
  survey_certification_sending/readme/USAGE.md
  survey_certification_sending/static/description/icon.png
  survey_certification_sending/static/description/index.html
  survey_certification_sending/tests/__init__.py
  survey_certification_sending/tests/test_survey_certification_sending.py
  survey_certification_sending/views/survey_survey_views.xml
  survey_certification_sending/views/survey_templates.xml
  survey_certification_sending/views/survey_user_views.xml
Labels: approved, bot is merging ⏳

#156 [15.0][ADD] survey_certification_py3o: New module
  setup/survey_certification_py3o/odoo/addons/survey_certification_py3o
  setup/survey_certification_py3o/setup.py
  survey_certification_py3o/README.rst
  survey_certification_py3o/__init__.py
  survey_certification_py3o/__manifest__.py
  survey_certification_py3o/controllers/__init__.py
  survey_certification_py3o/controllers/main.py
  survey_certification_py3o/demo/demo_report_certification.odt
  survey_certification_py3o/models/__init__.py
  survey_certification_py3o/models/mail_template.py
  survey_certification_py3o/models/py3o_report.py
  survey_certification_py3o/models/survey_survey.py
  survey_certification_py3o/models/survey_user_input.py
  survey_certification_py3o/readme/CONTRIBUTORS.rst
  survey_certification_py3o/readme/DESCRIPTION.rst
  survey_certification_py3o/readme/USAGE.rst
  survey_certification_py3o/static/description/index.html
  survey_certification_py3o/tests/__init__.py
  survey_certification_py3o/tests/test_survey_certification_py3o.py
  survey_certification_py3o/views/survey_reports.xml
  survey_certification_py3o/views/survey_survey_views.xml
Labels: bot is merging ⏳

#172 [15.0][FIX] survey_certification_py3o: Change conditions to generate report + test
  survey_certification_py3o/models/py3o_report.py
  survey_certification_py3o/tests/test_survey_certification_py3o.py
Labels: bot is merging ⏳

#173 [17.0][MIG] survey_certification_py3o: Migration to version 17.0
  survey_certification_py3o/README.rst
  survey_certification_py3o/__init__.py
  survey_certification_py3o/__manifest__.py
  survey_certification_py3o/controllers/__init__.py
  survey_certification_py3o/controllers/main.py
  survey_certification_py3o/demo/demo_report_certification.odt
  survey_certification_py3o/i18n/survey_certification_py3o.pot
  survey_certification_py3o/models/__init__.py
  survey_certification_py3o/models/mail_template.py
  survey_certification_py3o/models/py3o_report.py
  survey_certification_py3o/models/survey_survey.py
  survey_certification_py3o/models/survey_user_input.py
  survey_certification_py3o/pyproject.toml
  survey_certification_py3o/readme/CONTRIBUTORS.md
  survey_certification_py3o/readme/DESCRIPTION.md
  survey_certification_py3o/readme/USAGE.md
  survey_certification_py3o/static/description/icon.png
  survey_certification_py3o/static/description/index.html
  survey_certification_py3o/tests/__init__.py
  survey_certification_py3o/tests/test_survey_certification_py3o.py
  survey_certification_py3o/views/survey_reports.xml
  survey_certification_py3o/views/survey_survey_views.xml
Labels: approved, bot is merging ⏳

#175 [17.0][IMP] survey_certification_sending: authorise certificate download at contact level
  survey_certification_sending/README.rst
  survey_certification_sending/__manifest__.py
  survey_certification_sending/models/__init__.py
  survey_certification_sending/models/mail_template.py
  survey_certification_sending/models/res_partner.py
  survey_certification_sending/models/survey_user_input.py
  survey_certification_sending/tests/test_survey_certification_sending.py
  survey_certification_sending/views/res_partner_views.xml
  survey_certification_sending/views/survey_templates.xml
Labels: approved, bot is merging ⏳
