Repository OCA/survey, pull requests merged in 2025-04, with the labels that each got.

#158 [17.0][MIG] survey_result_mail: Migration to version 17.0
  survey_result_mail/README.rst
  survey_result_mail/__init__.py
  survey_result_mail/__manifest__.py
  survey_result_mail/data/mail_template.xml
  survey_result_mail/i18n/es.po
  survey_result_mail/i18n/it.po
  survey_result_mail/i18n/survey_result_mail.pot
  survey_result_mail/migrations/17.0.1.0.0/noupdate_changes.xml
  survey_result_mail/migrations/17.0.1.0.0/post-migration.py
  survey_result_mail/models/__init__.py
  survey_result_mail/models/survey_survey.py
  survey_result_mail/models/survey_user_input.py
  survey_result_mail/pyproject.toml
  survey_result_mail/readme/CONFIGURE.md
  survey_result_mail/readme/CONTRIBUTORS.md
  survey_result_mail/readme/DESCRIPTION.md
  survey_result_mail/readme/USAGE.md
  survey_result_mail/reports/survey_answer_report.xml
  survey_result_mail/static/description/icon.png
  survey_result_mail/static/description/index.html
  survey_result_mail/templates/survey_answer_templates.xml
  survey_result_mail/tests/__init__.py
  survey_result_mail/tests/test_survey_result_mail.py
  survey_result_mail/views/survey_survey_views.xml
  survey_result_mail/views/survey_user_input_views.xml
Labels: approved, bot is merging ⏳

#129 [17.0][MIG] survey_question_type_binary: Migration to 17.0
  .pre-commit-config.yaml
  survey_question_type_binary/README.rst
  survey_question_type_binary/__init__.py
  survey_question_type_binary/__manifest__.py
  survey_question_type_binary/i18n/it.po
  survey_question_type_binary/i18n/survey_question_type_binary.pot
  survey_question_type_binary/models/__init__.py
  survey_question_type_binary/models/survey_question.py
  survey_question_type_binary/models/survey_user_input.py
  survey_question_type_binary/models/survey_user_input_line.py
  survey_question_type_binary/models/survey_user_input_line_binary.py
  survey_question_type_binary/pyproject.toml
  survey_question_type_binary/readme/CONFIGURE.md
  survey_question_type_binary/readme/CONTRIBUTORS.md
  survey_question_type_binary/readme/DESCRIPTION.md
  survey_question_type_binary/security/ir.model.access.csv
  survey_question_type_binary/static/description/icon.png
  survey_question_type_binary/static/description/index.html
  survey_question_type_binary/static/src/js/survey_form.js
  survey_question_type_binary/templates/survey_template.xml
  survey_question_type_binary/tests/__init__.py
  survey_question_type_binary/tests/test_survey.py
  survey_question_type_binary/views/survey_question.xml
  survey_question_type_binary/views/survey_user_input_line.xml
Labels: needs review, approved, migration, bot is merging ⏳

#92 [15.0][ADD] survey_answer_generation: New module
  setup/survey_answer_generation/odoo/addons/survey_answer_generation
  setup/survey_answer_generation/setup.py
  survey_answer_generation/README.rst
  survey_answer_generation/__init__.py
  survey_answer_generation/__manifest__.py
  survey_answer_generation/i18n/es.po
  survey_answer_generation/i18n/survey_answer_generation.pot
  survey_answer_generation/models/__init__.py
  survey_answer_generation/models/survey_question.py
  survey_answer_generation/models/survey_survey.py
  survey_answer_generation/models/survey_user_input.py
  survey_answer_generation/readme/CONFIGURE.rst
  survey_answer_generation/readme/CONTRIBUTORS.rst
  survey_answer_generation/readme/DESCRIPTION.rst
  survey_answer_generation/readme/USAGE.rst
  survey_answer_generation/static/description/icon.png
  survey_answer_generation/static/description/index.html
  survey_answer_generation/views/survey_question_views.xml
  survey_answer_generation/views/survey_survey_views.xml
  survey_answer_generation/views/survey_user_input_views.xml
Labels: approved, bot is merging ⏳

#161 [17.0][MIG] survey_sale_generation: Migration to version 17.0
  survey_sale_generation/README.rst
  survey_sale_generation/__init__.py
  survey_sale_generation/__manifest__.py
  survey_sale_generation/demo/survey_sale_demo.xml
  survey_sale_generation/i18n/es.po
  survey_sale_generation/i18n/it.po
  survey_sale_generation/i18n/survey_sale_generation.pot
  survey_sale_generation/models/__init__.py
  survey_sale_generation/models/sale_order.py
  survey_sale_generation/models/survey_question.py
  survey_sale_generation/models/survey_survey.py
  survey_sale_generation/models/survey_user_input.py
  survey_sale_generation/pyproject.toml
  survey_sale_generation/readme/CONFIGURE.md
  survey_sale_generation/readme/CONTRIBUTORS.md
  survey_sale_generation/readme/DESCRIPTION.md
  survey_sale_generation/readme/USAGE.md
  survey_sale_generation/static/description/icon.png
  survey_sale_generation/static/description/index.html
  survey_sale_generation/static/tests/survey_sale_generation_tour.esm.js
  survey_sale_generation/tests/__init__.py
  survey_sale_generation/tests/test_survey_sale_generation.py
  survey_sale_generation/views/sale_order_views.xml
  survey_sale_generation/views/survey_question_views.xml
  survey_sale_generation/views/survey_survey_views.xml
  survey_sale_generation/views/survey_user_input_views.xml
Labels: approved, bot is merging ⏳

#163 [17.0][MIG] survey_multi_company: Migration to version 17.0
  survey_multi_company/README.rst
  survey_multi_company/__init__.py
  survey_multi_company/__manifest__.py
  survey_multi_company/i18n/it.po
  survey_multi_company/i18n/survey_multi_company.pot
  survey_multi_company/models/__init__.py
  survey_multi_company/models/survey_survey.py
  survey_multi_company/pyproject.toml
  survey_multi_company/readme/CONTRIBUTORS.md
  survey_multi_company/readme/DESCRIPTION.md
  survey_multi_company/readme/USAGE.md
  survey_multi_company/security/survey_security.xml
  survey_multi_company/static/description/icon.png
  survey_multi_company/static/description/index.html
  survey_multi_company/views/survey_views.xml
Labels: approved, bot is merging ⏳

#146 [15.0][ADD] survey_certification_sending: New module
  setup/survey_certification_sending/odoo/addons/survey_certification_sending
  setup/survey_certification_sending/setup.py
  survey_certification_sending/README.rst
  survey_certification_sending/__init__.py
  survey_certification_sending/__manifest__.py
  survey_certification_sending/i18n/es.po
  survey_certification_sending/i18n/survey_certification_sending.pot
  survey_certification_sending/migrations/15.0.1.0.0/post-migration.py
  survey_certification_sending/models/__init__.py
  survey_certification_sending/models/mail_template.py
  survey_certification_sending/models/survey_survey.py
  survey_certification_sending/models/survey_user_input.py
  survey_certification_sending/readme/CONTRIBUTORS.rst
  survey_certification_sending/readme/DESCRIPTION.rst
  survey_certification_sending/readme/USAGE.rst
  survey_certification_sending/static/description/index.html
  survey_certification_sending/tests/__init__.py
  survey_certification_sending/tests/test_survey_certification_sending.py
  survey_certification_sending/views/survey_survey_views.xml
  survey_certification_sending/views/survey_templates.xml
  survey_certification_sending/views/survey_user_views.xml
Labels: bot is merging ⏳
