Repository OCA/survey, pull requests merged in 2025-06, with the labels that each got.

#73 [MIG] survey_xlsx: Migration to 15.0
  setup/survey_xlsx/odoo/addons/survey_xlsx
  setup/survey_xlsx/setup.py
  survey_xlsx/README.rst
  survey_xlsx/__init__.py
  survey_xlsx/__manifest__.py
  survey_xlsx/i18n/it.po
  survey_xlsx/i18n/survey_xlsx.pot
  survey_xlsx/models/__init__.py
  survey_xlsx/models/survey_user_input_line.py
  survey_xlsx/readme/CONTRIBUTORS.rst
  survey_xlsx/readme/DESCRIPTION.rst
  survey_xlsx/report/__init__.py
  survey_xlsx/report/report_survey_xlsx.py
  survey_xlsx/report/report_survey_xlsx.xml
  survey_xlsx/static/description/icon.png
  survey_xlsx/static/description/index.html
  survey_xlsx/tests/__init__.py
  survey_xlsx/tests/test_report.py
Labels: approved, bot is merging ⏳, stale

#140 [16.0][MIG] survey_contact_generation: Migration to 16.0
  setup/survey_contact_generation/odoo/addons/survey_contact_generation
  setup/survey_contact_generation/setup.py
  survey_contact_generation/README.rst
  survey_contact_generation/__init__.py
  survey_contact_generation/__manifest__.py
  survey_contact_generation/demo/survey_contact_generation_demo.xml
  survey_contact_generation/i18n/es.po
  survey_contact_generation/i18n/it.po
  survey_contact_generation/i18n/survey_contact_generation.pot
  survey_contact_generation/models/__init__.py
  survey_contact_generation/models/res_partner.py
  survey_contact_generation/models/survey_question.py
  survey_contact_generation/models/survey_survey.py
  survey_contact_generation/models/survey_user_input.py
  survey_contact_generation/readme/CONFIGURE.rst
  survey_contact_generation/readme/CONTRIBUTORS.rst
  survey_contact_generation/readme/DESCRIPTION.rst
  survey_contact_generation/readme/USAGE.rst
  survey_contact_generation/static/description/icon.png
  survey_contact_generation/static/description/index.html
  survey_contact_generation/static/tests/survey_contact_generation_tour.js
  survey_contact_generation/tests/__init__.py
  survey_contact_generation/tests/test_survey_contact_generation.py
  survey_contact_generation/tests/test_survey_question.py
  survey_contact_generation/tests/test_survey_user_input.py
  survey_contact_generation/views/survey_question_views.xml
  survey_contact_generation/views/survey_survey_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#162 [16.0] [ADD] survey_certification_branding: support custom company name and logo in certification report
  setup/survey_certification_branding/odoo/addons/survey_certification_branding
  setup/survey_certification_branding/setup.py
  survey_certification_branding/README.rst
  survey_certification_branding/__init__.py
  survey_certification_branding/__manifest__.py
  survey_certification_branding/i18n/es.po
  survey_certification_branding/i18n/survey_certification_branding.pot
  survey_certification_branding/models/__init__.py
  survey_certification_branding/models/survey_survey.py
  survey_certification_branding/readme/CONTRIBUTORS.md
  survey_certification_branding/readme/DESCRIPTION.md
  survey_certification_branding/readme/USAGE.md
  survey_certification_branding/report/survey_report_templates.xml
  survey_certification_branding/static/description/certification_branding_section.png
  survey_certification_branding/static/description/icon.png
  survey_certification_branding/static/description/index.html
  survey_certification_branding/tests/__init__.py
  survey_certification_branding/tests/test_survey_certification_branding.py
  survey_certification_branding/views/survey_survey_views.xml
Labels: approved, bot is merging ⏳
